export default [
  {
    name: "ARANZADO, MICHAEL, QUEROL",
    wiresign: "AZ",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Mangubat, Michael, Alimpolos",
    wiresign: "XP",
    day0: "AM,PM",
    day1: "AM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Gaspan, Eugene A.",
    wiresign: "EU",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "PM",
    day3: "AM,PM",
  },
  {
    name: "CUETO, EDGARDO CODILLA",
    wiresign: "RM",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "FIGUEROA, GASPAR FALLE",
    wiresign: "GF",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Rogado, Aldrin Joshua, Igtiben",
    wiresign: "QJ",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Daclan,Percival S",
    wiresign: "VD",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Petilo, Jhedson Angelo",
    wiresign: "WY",
    day0: "AM,PM",
    day1: "FALSE",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Buena Jr., Jose Alexander, Folloso",
    wiresign: "LX",
    day0: "AM,PM",
    day1: "AM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Mabulay, Neil Urian, Secretaria",
    wiresign: "NU",
    day0: "AM,PM",
    day1: "AM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Sullivan, Tamya Lemuria, Tayam",
    wiresign: "TS",
    day0: "AM,PM",
    day1: "AM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Bajar, Mares Vily, Baroña",
    wiresign: "VZ",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Felipe, Alejandro Matias",
    wiresign: "AK",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Martizon, John Arthur, Nisperos",
    wiresign: "MQ",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "BELDUA, ERVIN BIEN AGUADO",
    wiresign: "BV",
    day0: "AM,PM",
    day1: "AM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "ILAGAN, RODEL PANALIGAN",
    wiresign: "IR",
    day0: "AM,PM",
    day1: "AM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Altillo, Lucas Hablado",
    wiresign: "LA",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Singco, Maricor Lalosa",
    wiresign: "NX",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Aguila Marfe Goot",
    wiresign: "MM",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "GUELOS, ALLAN AYENTO",
    wiresign: "YM",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "Masigon, Jan-Michael Repolito",
    wiresign: "MT",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "Retome, Hanna A",
    wiresign: "HX",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "Rodulfa, Jasmin, Sanchez",
    wiresign: "ZW",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "MANIGSACA, RIC BELANDEES",
    wiresign: "GX",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "FALSE",
  },
  {
    name: "Andrada, Fermin Legaspi",
    wiresign: "AN",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "FALSE",
  },
  {
    name: "BARRIOS, JEROME TORRE",
    wiresign: "BR",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "Butalon, Maria Merly, Bagtilay",
    wiresign: "BS",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Baliong, Aileen, Araneta",
    wiresign: "QA",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Latip, Junnamin Dongklang",
    wiresign: "OF",
    day0: "PM",
    day1: "AM,PM",
    day2: "PM",
    day3: "FALSE",
  },
  {
    name: "Platon, Mila Caballero",
    wiresign: "JS",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "FALSE",
  },
  {
    name: "Sanchez, Jessie, Fernandez",
    wiresign: "QS",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Garan, Joy Vallejera",
    wiresign: "YS",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "FALSE",
  },
  {
    name: "Talaran, Edriel Joseph Tubianosa",
    wiresign: "XT",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "PM",
    day3: "FALSE",
  },
  {
    name: "Madrid, Michael Dichoso",
    wiresign: "MK",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Patilla, Josephine Francisco",
    wiresign: "EF",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Maglahus, Rodrigo E.",
    wiresign: "BM",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Balbuena, RJ Faith, Villaflor",
    wiresign: "RJ",
    day0: "AM,PM",
    day1: "AM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Urbiztondo, Renan Joseph Ibarra",
    wiresign: "QZ",
    day0: "AM,PM",
    day1: "AM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Duroy, Junemel Lupot",
    wiresign: "YJ",
    day0: "AM,PM",
    day1: "AM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Duque, Pia Shane Alcoseba",
    wiresign: "DQ",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "PM",
    day3: "FALSE",
  },
  {
    name: "Amorsolo, Aileen, Lumagbas",
    wiresign: "AI",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "Fontecha, Kharen Guhit",
    wiresign: "ax",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Estrada, Cristina Ragudo",
    wiresign: "CE",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Sullivan, Philip C",
    wiresign: "FS",
    day0: "AM,PM",
    day1: "FALSE",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "De Felipe, Richard Anthony, Dagsa",
    wiresign: "LE",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "PM",
    day3: "AM",
  },
  {
    name: "Rodriguez, Mary Grace Casiano",
    wiresign: "UZ",
    day0: "AM,PM",
    day1: "FALSE",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Santillana Hermogenes Abaygar",
    wiresign: "AH",
    day0: "AM,PM",
    day1: "FALSE",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Alas, Richard Zerda",
    wiresign: "RX",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "BANDILLA, ROGER, AYON",
    wiresign: "BA",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "FABULAR, BRIAN, ALCARAZ",
    wiresign: "BF",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "PRESNILLA, MIGUEL JR., FABILANE",
    wiresign: "RX",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "mark david costelo",
    wiresign: "UB",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Marie Anabelle Bilagot",
    wiresign: "XZ",
    day0: "FALSE",
    day1: "PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Chuan, Jondee li Escabas",
    wiresign: "IF",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "ESPEDILLON, RHEA LYN MONDEJAR",
    wiresign: "VP",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "MALTE, MA. FE LIMSIACO",
    wiresign: "BM",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "DELA CRUZ, MARY ANN, CONCEPCION",
    wiresign: "XX",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "RODRIGUEZ, EMMANUEL TABINGA",
    wiresign: "ZT",
    day0: "FALSE",
    day1: "PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Balbino Lailane Dagot",
    wiresign: "LI",
    day0: "FALSE",
    day1: "PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Cave, Ryan Salen",
    wiresign: "RN",
    day0: "FALSE",
    day1: "PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Rodriguez, Nathaniel Tabarangao",
    wiresign: "NR",
    day0: "FALSE",
    day1: "PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "LOQUIB, ERLINDA BATARINO",
    wiresign: "ZU",
    day0: "FALSE",
    day1: "PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Cipriano, Virgilio Reyes",
    wiresign: "RV",
    day0: "FALSE",
    day1: "PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "BUTIAL ALMIRA ORBITA",
    wiresign: "MI",
    day0: "FALSE",
    day1: "FALSE",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Ventura,Delia,Niño",
    wiresign: "DV",
    day0: "FALSE",
    day1: "FALSE",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Fernandez, Himelie Ledesma",
    wiresign: "HS",
    day0: "FALSE",
    day1: "FALSE",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Gayosa, Mary Ann Grace Ozoa",
    wiresign: "GO",
    day0: "FALSE",
    day1: "FALSE",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Jimenez, Juliet Marcos",
    wiresign: "AM",
    day0: "FALSE",
    day1: "FALSE",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Lao Christopher Galicia",
    wiresign: "PL",
    day0: "FALSE",
    day1: "FALSE",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Lingatong, Edgardo Marbibi",
    wiresign: "LM",
    day0: "FALSE",
    day1: "FALSE",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Rodrigo, Renz Carlo, Manaloto",
    wiresign: "WR",
    day0: "FALSE",
    day1: "FALSE",
    day2: "PM",
    day3: "AM,PM",
  },
  {
    name: "Ferriols, luis ramon",
    wiresign: "RF",
    day0: "FALSE",
    day1: "FALSE",
    day2: "PM",
    day3: "AM,PM",
  },
  {
    name: "DE GARCIA, SHEAN",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Andrada, Sarah Jane",
    wiresign: "QD",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "PM",
    day3: "AM",
  },
  {
    name: "Damasco, Rosalina",
    wiresign: "RO",
    day0: "PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Perez, Sharon B.",
    wiresign: "SB",
    day0: "PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "CUEVAS, JASPER CHRISTIAN",
    wiresign: "XI",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Villacarlos, Raymond",
    wiresign: "WT",
    day0: "AM,PM",
    day1: "FALSE",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Villacarlos,Beverly Grace",
    wiresign: "BG",
    day0: "AM,PM",
    day1: "FALSE",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Gapuzan, Albert R.",
    wiresign: "GX",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "Chiefe, Anna Liza",
    wiresign: "CP",
    day0: "FALSE",
    day1: "PM",
    day2: "AM,PM",
    day3: "FALSE",
  },
  {
    name: "Rebaya, Kristoffer",
    wiresign: "KA",
    day0: "FALSE",
    day1: "FALSE",
    day2: "PM",
    day3: "AM,PM",
  },
  {
    name: "TYRON ARIAS",
    wiresign: "KX",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "EDGAR ESTRIVO",
    wiresign: "SV",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "Rudy Boctot Jr",
    wiresign: "YY",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Panganiban, Zohara Buza",
    wiresign: "ZX",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Artiga, Samantha Mei Bautista",
    wiresign: "SA",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "BAUTISTA CHARLWIN ACORDA",
    wiresign: "GG",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Bona, Hosni, Macrohon",
    wiresign: "HK",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Bue, Joana Marie, Tecson",
    wiresign: "JU",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Bulseco, Renz Marione, Metran",
    wiresign: "ZY",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Garcia, Kevin Charles, Daep",
    wiresign: "KV",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Hermosilla, Alfred Martin",
    wiresign: "HL",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Munda, Keff Jester T",
    wiresign: "KN",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Nicolas, Noel Jr, Laurente",
    wiresign: "NL",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Marcelino, Anna Marie Pioquinto",
    wiresign: "HW",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "YAP, KENNETH LOUIES",
    wiresign: "EX",
    day0: "AM,PM",
    day1: "FALSE",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Cabueñas, Aaron Timothy Balzomo",
    wiresign: "TC",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Candare, Christine Rodulfo",
    wiresign: "IU",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Fuentes, Imelee Ureta",
    wiresign: "YX",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "JUAN, RACHEL MAYGRACE AGUSTIN",
    wiresign: "LJ",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Nacorda, Venna Christine Alvarico",
    wiresign: "VE",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Orot, Krishiele Mei, Golez",
    wiresign: "HI",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "Tapia Glenna Joy Baided",
    wiresign: "GJ",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "Bernolia, Ma. Katrine Dianne, Barcelona",
    wiresign: "KD",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Bonales, Ricca Danica H.",
    wiresign: "CC",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Conjusta, Louise Valerie Fajunio",
    wiresign: "CT",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Moriles, Joy, Galino",
    wiresign: "SG",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Oporto, Therese Rhoda",
    wiresign: "WT",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Paciones, Zenia Uy",
    wiresign: "YZ",
    day0: "PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Ventivingo, Alicia Kayla Dominique Umerez",
    wiresign: "VH",
    day0: "PM",
    day1: "AM,PM",
    day2: "PM",
    day3: "AM",
  },
  {
    name: "Pepito, Albert Aballe",
    wiresign: "ZP",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "PM",
  },
  {
    name: "Hurtado, Cecile, Hibionada",
    wiresign: "HC",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Flores, Jannica Rivera",
    wiresign: "ZB",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Milanes, Sussannah Condes",
    wiresign: "ZS",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Palaran, Jairus, Coroza",
    wiresign: "XJ",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "FALSE",
  },
  {
    name: "salmasan noel mariano",
    wiresign: "zz",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "PM",
    day3: "AM",
  },
  {
    name: "RAMILLA, PHAILIN RIVERA",
    wiresign: "PH",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "PM",
    day3: "AM,PM",
  },
  {
    name: "Soneja, Wendee, Barba",
    wiresign: "QW",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Estares, Marlyn Hingpit",
    wiresign: "SJ",
    day0: "FALSE",
    day1: "PM",
    day2: "PM",
    day3: "AM,PM",
  },
  {
    name: "Bolhayon, Bronzon Yogyog",
    wiresign: "RH",
    day0: "FALSE",
    day1: "PM",
    day2: "PM",
    day3: "AM,PM",
  },
  {
    name: "AVENGOZA MARIA CECILIA PASCUHIN",
    wiresign: "ZQ",
    day0: "FALSE",
    day1: "FALSE",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Hurtado, Edward Joseph, Basto",
    wiresign: "DJ",
    day0: "FALSE",
    day1: "FALSE",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Fetalvero, David Leoriz Germinal",
    wiresign: "XY",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Mangonon, Leslie Marie, Nebrija",
    wiresign: "LK",
    day0: "FALSE",
    day1: "FALSE",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Servito, Eljun Rionel Panganiban",
    wiresign: "ER",
    day0: "FALSE",
    day1: "FALSE",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "pasaje arlene d.",
    wiresign: "by",
    day0: "FALSE",
    day1: "FALSE",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Bulseco, Jose Renwick V",
    wiresign: "RB",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "LALUGAN, RUBY ANNA",
    wiresign: "YB",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Saunders, Aira May Ann",
    wiresign: "SEC",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "PM",
    day3: "AM",
  },
  {
    name: "Miguel, Mary Ann",
    wiresign: "SEC",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "PM",
    day3: "AM",
  },
  {
    name: "MONTAÑO, Mark Leonile",
    wiresign: "UT",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "FALSE",
  },
  {
    name: "Santos, Jaime Vicente Salvador",
    wiresign: "VX",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Salomon , Jonathan",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "FALSE",
  },
  {
    name: "Dalimot, Marvin",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Doblas, Nievie P.",
    wiresign: "ND",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Bongoyan, Kyra Maureen D.",
    wiresign: "IK",
    day0: "AM,PM",
    day1: "AM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Guanzon, Kristine Mae S.",
    wiresign: "GH",
    day0: "AM,PM",
    day1: "AM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Dela Cruz, Mary Ann Z.",
    wiresign: "XO",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Hortillosa, Noel Jr.",
    wiresign: "XL",
    day0: "FALSE",
    day1: "FALSE",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "CLAVERIA, MIKE MATTHEW IAN",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Albano, Arlene",
    wiresign: "ZA",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Yu, Elito JR",
    wiresign: "EY",
    day0: "FALSE",
    day1: "PM",
    day2: "PM",
    day3: "FALSE",
  },
  {
    name: "Hidalgo, Maria Theresa",
    wiresign: "MT",
    day0: "PM",
    day1: "AM,PM",
    day2: "PM",
    day3: "AM",
  },
  {
    name: "Comahig, Erica",
    wiresign: "EV",
    day0: "PM",
    day1: "AM,PM",
    day2: "PM",
    day3: "FALSE",
  },
  {
    name: "Algara, Rommel",
    wiresign: "RA",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Bagsican, Ian",
    wiresign: "XB",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "Algara, Maria Golda",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Jumao-as, Josephus",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "AM",
  },
  {
    name: "Eugenio, Maria Felicidad V.",
    wiresign: "VA",
    day0: "FALSE",
    day1: "FALSE",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "Diones, Christie Joan D.",
    wiresign: "JX",
    day0: "FALSE",
    day1: "FALSE",
    day2: "FALSE",
    day3: "AM",
  },
  {
    name: "Galan, Florentino Jr.",
    wiresign: "CF",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "PM",
    day3: "AM",
  },
  {
    name: "Tapusok, Alain",
    wiresign: "FC",
    day0: "AM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Dela Peña, Josepine",
    wiresign: "AM",
    day0: "AM",
    day1: "FALSE",
    day2: "PM",
    day3: "AM",
  },
  {
    name: "Mantilla, Leo",
    wiresign: "WX",
    day0: "AM",
    day1: "PM",
    day2: "PM",
    day3: "AM",
  },
  {
    name: "Elumba, Bella",
    wiresign: "WZ",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "Boholst, Vernilyn",
    wiresign: "US",
    day0: "PM",
    day1: "AM,PM",
    day2: "PM",
    day3: "AM",
  },
  {
    name: "Arado, Steven",
    wiresign: "WC",
    day0: "AM,PM",
    day1: "FALSE",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Manantan, Ma. Dolores",
    wiresign: "SF",
    day0: "PM",
    day1: "AM,PM",
    day2: "PM",
    day3: "AM",
  },
  {
    name: "Ople, Arturo",
    wiresign: "TN",
    day0: "PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Cabahug, Jovanni",
    wiresign: "KO",
    day0: "PM",
    day1: "FALSE",
    day2: "PM",
    day3: "FALSE",
  },
  {
    name: "Dalimot, Alma",
    day0: "AM,PM",
    day1: "FALSE",
    day2: "FALSE",
    day3: "PM",
  },
  {
    name: "Mercado, Ivilyn",
    day0: "AM",
    day1: "FALSE",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "SINGSON, MARLENE",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM",
  },
  {
    name: "MONTAÑO, LEONITO",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "PM",
    day3: "AM,PM",
  },
  {
    name: "ANTONIO, GONZALES",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "ALFONSO, ANTONIO",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "JESSICA JAMERO",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "ERWIN JAMERO",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "JOY PAPAG",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "MELBA ACURANTES",
    day0: "PM",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "NICKSON MORADA",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "DOTR +2",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "DDGO +2",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "VANNIE GABRIEL",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "AM",
    day3: "FALSE",
  },
  {
    name: "PAENG TATLONGHARI",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "DOT Director-Vern Buensuceso",
    day0: "FALSE",
    day1: "FALSE",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Attty. Jinky Ang",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "DOT CEBU",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Col. Val Dionela ADMS",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "Capt. Don Mendoza FSIS",
    day0: "FALSE",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "ASIAN SAFARRI 1",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "ASIAN SAFARRI 2",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "AM,PM",
    day3: "AM,PM",
  },
  {
    name: "Capt. Jim Sydiongco",
    day0: "PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
  {
    name: "DDGA Atty. Danjun",
    day0: "AM,PM",
    day1: "AM,PM",
    day2: "FALSE",
    day3: "FALSE",
  },
];
